---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrap-gpu
spec:
  backoffLimit: 3
  schedule: "5 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: {{ .Values.gpus.registry }}
          containers:
          - name: needpc-scrap-gpu
            image: quay.io/perriea/needpc-scrap:0.0.2
            command:
            - scrap:gpu --trace
            env:
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: database
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: password
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: host
          restartPolicy: OnFailure