---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrap-ldlc
spec:
  backoffLimit: 3
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullPolicy: {{ .Values.cronjobs.pullPolicy }}
          imagePullSecrets:
            - name: {{ .Values.cronjobs.registry }}
          containers:
          - name: needpc-scrap-ldlc
            image: {{ .Values.cronjobs.repository }}:{{ .Values.cronjobs.tag }}
            command:
            - scrap:ldlc --trace
            env:
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: database
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: password
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: host
          restartPolicy: Never

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrap-fnac
spec:
  backoffLimit: 3
  schedule: "30 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullPolicy: {{ .Values.cronjobs.pullPolicy }}
          imagePullSecrets:
            - name: {{ .Values.cronjobs.registry }}
          containers:
          - name: needpc-scrap-fnac
            image: {{ .Values.cronjobs.repository }}:{{ .Values.cronjobs.tag }}
            command:
            - scrap:fnac --trace
            env:
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: database
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: password
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: host
          restartPolicy: Never

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: scrap-topachat
spec:
  backoffLimit: 3
  schedule: "40 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: {{ .Values.cronjobs.registry }}
          containers:
          - name: needpc-scrap-topachat
            image: {{ .Values.cronjobs.repository }}:{{ .Values.cronjobs.tag }}
            command:
            - scrap:topchat --trace
            env:
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: database
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: password
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: database-config
                  key: host
          restartPolicy: Never