---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "frontend.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/cors-allow-methods: "HEAD, GET"
    nginx.ingress.kubernetes.io/cors-allow-origin: https://www.needpc.fr,https://m.needpc.fr
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: www.needpc.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "frontend.fullname" . }}
          servicePort: 80
  - host: m.needpc.fr
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "frontend.fullname" . }}
          servicePort: 80