# Default values for computers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# HPA
minReplicaCount: 2
maxReplicaCount: 4

# Namespace
namespace: needpc

# Deployment
computers:
  hostname: computers
  repository: quay.io/needpc/needpc-api-computers
  tag: 0.0.4
  pullPolicy: IfNotPresent
  registry: needpc-k8s-pull-secret

# Cronjob
cronjobs:
  repository: quay.io/perriea/needpc-scrap
  tag: 0.0.3
  pullPolicy: IfNotPresent
  registry: needpc-k8s-pull-secret

redis:
  hostname: redis
  repository: redis
  tag: 4.0-alpine
  pullPolicy: IfNotPresent

# Service
service:
  type: ClusterIP
  containerPort: 3000
  port: 80

computers_resources:
  limits:
   cpu: 200m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 64Mi

redis_resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
