# Default values for ask.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# HPA
minReplicaCount: 2
maxReplicaCount: 4

# Namespace
namespace: needpc

# Deployment
ask:
  hostname: ask
  repository: quay.io/needpc/needpc-api-ask
  tag: 0.0.2
  pullPolicy: IfNotPresent
  registry: needpc-k8s-pull-secret

# Service
service:
  type: ClusterIP
  containerPort: 3000
  port: 80

ask_resources:
  limits:
   cpu: 200m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
